### ISSUE TITLE
Getting "result ciphertext is transparent" error while inferencing..

### ISSUE THREAD

**Issue by mayank64ce** [LiangqinRen/PrivDNN#1]
Hello, I am new to FHE and am trying to learn about your code.

I ran the inference on MNIST as instructed [here](https://github.com/LiangqinRen/PrivDNN#inference) by changing the `MNIST/inference_encrypted_neurons.json` file to `{"1": [0], "2": [0]}`  and then used `bash run.sh mnist inference` but I got the following error:

```bash
[2024-04-30 10:55:02.892][  utils.py: 199][ INFO]|Parameter configuration:
	dataset: MNIST
	log_level: 20
	work_mode: WorkMode.fhe_inference
	sub_work_mode: None
	top_k_accuracy: 1
	train_dataset_percent: None
	selected_neurons_file: None
	initial_layer_index: None
	encrypt_layers_count: None
	initial_layer_neurons: None
	add_factor: None
	multiply_factor: None
	percent_factor: None
	accuracy_base: None
	greedy_step: None
	recover_dataset_percent: None
	recover_dataset_count: None
	recover_freeze: False

[2024-04-30 10:55:03.005][   main.py:  83][ INFO]|SEAL separate inference:
Selected neurons of MNIST: {"1":[0],"2":[0]}
terminate called after throwing an instance of 'std::logic_error'
  what():  result ciphertext is transparent
run.sh: line 74: 152519 Aborted                 (core dumped) python ../PrivDNN/main.py --dataset $dataset --work_mode 5 --top_k_accuracy ${top_k_accuracy[$dataset]}
```

What can I do to fix it ?

**Comment by LiangqinRen** [comment]
Hi, I tested it with a clean environment from the beginning, but everything works well. The error could be caused by many reasons, such as giving incorrect parameters, but you don't need to change my parameters, and it works well in my environment. Besides, the key part of this repository is the select algorithm. If you want to learn FHE, I recommend reading and running the SEAL repository examples.
