### ISSUE TITLE
How to encrypt the entire network while inferencing ?

### ISSUE THREAD

**Issue by mayank64ce** [LiangqinRen/PrivDNN#2]

**Comment by LiangqinRen** [comment]
Hi, we can control the selected neurons with the file *inference_encrypted_neurons.json*. However, our selection only applies to convolutional layers because other layers, like the linear layer, will use all previous neurons, so we can't encrypt partial neurons. If you only want to encrypt all conv neurons,  you can set this file to select all neurons. If you want to encrypt the whole network with later linear layers, you can uncomment the codes in the main file about "CppWorkMode.full". However, I only implemented this with MNIST, and it was extremely slow (5000 seconds in my environment).

**Comment by mayank64ce** [comment]
thanks for the quick response. So is that what the `MNIST_128_128_100_cpp.pth` file does ? 

Another question I had is what exactly do the values inside `[]` in `{"1": [], "2": []}` mean ? Can you explain with a small example ?

**Comment by LiangqinRen** [comment]
I have two model files, i.e., MNIST_128_128_100.pth and MNIST_128_128_100_cpp.pth The difference is the first one is used to encrypt partial neurons in the convolutional layer, and the second one is used to encrypt the whole model. I use two models because when I implemented the first one, I used the ReLU function as the activation function of linear layers. However, when I needed to encrypt the whole model, I had to use the square function, so I trained another model, i.e., MNIST_128_128_100_cpp. The JSON file is the selected neurons starting from 0. For example, {"1": [0,1,2], "2": [0,1,2]} means you want to select the neurons 0,1,2 in the first two layers.
